graph TD
    A[スタート] --> B{プレイスタイル?}
    B -->|攻撃的| C{主な攻撃方法?}
    B -->|守備的| D{得意なショット?}
    B -->|オールラウンド| E{得意な場所?}

    C -->|スマッシュ/ドライブ| F{パワー重視?}
    C -->|スピン| G{回転重視?}
    C -->|ボレー| H{反応速度重視?}

    D -->|ロブ| I{高い打点重視?}
    D -->|スライス| J{低い打点重視?}
    D -->|カウンター| K{安定性重視?}

    E -->|ベースライン| L{オールコート性能?}
    E -->|ネット際| M{マニューバビリティ?}
    E -->|どこでも| N{バランス重視?}

    F -->|はい| O1{打球感重視?}
    F -->|いいえ| P1{スピンも重要?}

    G -->|はい| Q1{コントロールも必要?}
    G -->|いいえ| R1{得意なショットは?}

    H -->|はい| S1{打球感重視?}
    H -->|いいえ| T1{コート面の変化に対応?}

    I -->|はい| U1{スピンの強さは?}
    I -->|いいえ| V1{返球の安定性は?}

    J -->|はい| W1{スピン重視?}
    J -->|いいえ| X1{適応力重視?}

    K -->|はい| Y1{スピード重視?}
    K -->|いいえ| Z1{打球感重視?}

    L -->|はい| AA1{バランス重視?}
    L -->|いいえ| AB1{特定面用?}

    M -->|はい| AC1{スピード重視?}
    M -->|いいえ| AD1{コントロール重視?}

    N -->|はい| AE1{オールラウンド性能?}
    N -->|いいえ| AF1{個別のニーズに応じて選択}

    O1 -->|はい| O2[ラケット: 重め・硬い, ラバー: 高反発・厚め<br/>パワーと打球感のバランスが良い攻撃的セットアップ]
    O1 -->|いいえ| O3[ラケット: 重め・硬い, ラバー: 超高反発<br/>最大パワーを発揮する攻撃的セットアップ]
    P1 -->|はい| P2[ラケット: 中重量, ラバー: 高反発・高摩擦<br/>スピードとスピンを兼ね備えた攻撃的セットアップ]
    P1 -->|いいえ| P3[ラケット: 中重量, ラバー: 高反発・低摩擦<br/>純粋なスピード重視の攻撃的セットアップ]
    Q1 -->|はい| Q2[ラケット: 軽め, ラバー: 高摩擦・中反発<br/>スピン重視でコントロールも良い攻撃的セットアップ]
    Q1 -->|いいえ| Q3[ラケット: 軽め, ラバー: 超高摩擦<br/>最大スピンを生み出す攻撃的セットアップ]
    R1 -->|ドライブ| R2[ラケット: 中重量, ラバー: 中反発・高摩擦<br/>ドライブに適したオールラウンド攻撃用セットアップ]
    R1 -->|カット| R3[ラケット: 中重量, ラバー: 低反発・高摩擦<br/>カットに適したオールラウンド守備用セットアップ]
    S1 -->|はい| S2[ラケット: 超軽量, ラバー: 薄め<br/>俊敏で繊細な打球感のネットプレイ用セットアップ]
    S1 -->|いいえ| S3[ラケット: 軽め, ラバー: 中程度の厚さ<br/>バランスの取れたネットプレイ用セットアップ]
    T1 -->|はい| T2[ラケット: 軽め, ラバー: オールラウンド<br/>様々な状況に対応できるネットプレイ用セットアップ]
    T1 -->|いいえ| T3[ラケット: 軽め, ラバー: 特定面用<br/>特定のプレイ環境に適したネットプレイ用セットアップ]
    U1 -->|強い| U2[ラケット: 長め, ラバー: 長粒OX<br/>最大スピン変化を生む守備的セットアップ]
    U1 -->|普通| U3[ラケット: 長め, ラバー: 長粒スポンジ付き<br/>コントロール重視の守備的セットアップ]
    V1 -->|高い| V2[ラケット: 標準サイズ, ラバー: 粒高<br/>安定性重視の守備的セットアップ]
    V1 -->|普通| V3[ラケット: 標準サイズ, ラバー: 中粒<br/>バランスの取れた守備的セットアップ]
    W1 -->|はい| W2[ラケット: ヘッドライト, ラバー: 高摩擦<br/>スピン重視のスライス用セットアップ]
    W1 -->|いいえ| W3[ラケット: ヘッドライト, ラバー: 中程度の摩擦<br/>コントロール重視のスライス用セットアップ]
    X1 -->|はい| X2[ラケット: バランス型, ラバー: オールラウンド<br/>様々な守備スタイルに対応できるセットアップ]
    X1 -->|いいえ| X3[ラケット: バランス型, ラバー: 特定スタイル用<br/>特定の守備スタイルに特化したセットアップ]
    Y1 -->|はい| Y2[ラケット: ヘッドヘビー, ラバー: 攻撃用アンチ<br/>攻撃的なカウンター用セットアップ]
    Y1 -->|いいえ| Y3[ラケット: ヘッドヘビー, ラバー: 守備用アンチ<br/>守備的なカウンター用セットアップ]
    Z1 -->|はい| Z2[ラケット: バランス型, ラバー: 薄め<br/>繊細な打球感のカウンター用セットアップ]
    Z1 -->|いいえ| Z3[ラケット: バランス型, ラバー: 中程度の厚さ<br/>バランスの取れたカウンター用セットアップ]
    AA1 -->|はい| AA2[ラケット: オーバーサイズ, ラバー: オールラウンド<br/>オールコート用のバランス型セットアップ]
    AA1 -->|いいえ| AA3[ラケット: オーバーサイズ, ラバー: 特化型<br/>オールコート用の特定スタイル重視セットアップ]
    AB1 -->|はい| AB2[ラケット: ミッドプラス, ラバー: 特定面用<br/>特定コートエリアに特化したセットアップ]
    AB1 -->|いいえ| AB3[ラケット: ミッドプラス, ラバー: 汎用性高<br/>特定エリアでも汎用性の高いセットアップ]
    AC1 -->|はい| AC2[ラケット: 軽量コンパクト, ラバー: 高反発・薄め<br/>高速・軽量なネットプレイ用セットアップ]
    AC1 -->|いいえ| AC3[ラケット: 軽量コンパクト, ラバー: 中反発・薄め<br/>コントロール重視のネットプレイ用セットアップ]
    AD1 -->|はい| AD2[ラケット: 標準重量, ラバー: 中反発・中厚<br/>コントロール重視の標準的セットアップ]
    AD1 -->|いいえ| AD3[ラケット: 標準重量, ラバー: 高反発・中厚<br/>パワー重視の標準的セットアップ]
    AE1 -->|はい| AE2[ラケット: 中重量バランス型, ラバー: オールラウンド<br/>汎用性の高いオールラウンドセットアップ]
    AE1 -->|いいえ| AE3[ラケット: 中重量バランス型, ラバー: バランス型特化<br/>バランス重視の特化型セットアップ]
    AF1 --> AF2[ラケット・ラバー: 個別にカスタマイズ<br/>プレイヤーの特性に完全に合わせたセットアップ]