graph TD
    A[スタート] --> B{プレイスタイル?}
    B -->|攻撃的| C{主な攻撃方法?}
    B -->|守備的| D{得意なショット?}
    B -->|オールラウンド| E{得意な場所?}

    C -->|スマッシュ/ドライブ| F{パワー重視?}
    C -->|スピン| G{回転重視?}
    C -->|ボレー| H{反応速度重視?}

    D -->|ロブ| I{高い打点重視?}
    D -->|スライス| J{低い打点重視?}
    D -->|カウンター| K{安定性重視?}

    E -->|ベースライン| L{オールコート性能?}
    E -->|ネット際| M{マニューバビリティ?}
    E -->|どこでも| N{バランス重視?}

    F -->|はい| O[重めの硬いラケット]
    F -->|いいえ| P[中重量のラケット]

    G -->|はい| Q[軽めのラケット]
    G -->|いいえ| R[中重量ラケット]

    H -->|はい| S[超軽量ラケット]
    H -->|いいえ| T[軽めのラケット]

    I -->|はい| U[長めのラケット]
    I -->|いいえ| V[標準サイズラケット]

    J -->|はい| W[ヘッドライトラケット]
    J -->|いいえ| X[バランス型ラケット]

    K -->|はい| Y[ヘッドヘビーラケット]
    K -->|いいえ| Z[バランス型ラケット]

    L -->|はい| AA[オーバーサイズラケット]
    L -->|いいえ| AB[ミッドプラスサイズラケット]

    M -->|はい| AC[軽量コンパクトラケット]
    M -->|いいえ| AD[標準重量ラケット]

    N -->|はい| AE[中重量バランス型ラケット]
    N -->|いいえ| AF[個人の好みに応じてカスタマイズ]

    O --> O1{打球感重視?}
    P --> P1{スピンも重要?}
    Q --> Q1{コントロールも必要?}
    R --> R1{得意なショットは?}
    S --> S1{打球感重視?}
    T --> T1{コート面の変化に対応?}
    U --> U1{スピンの強さは?}
    V --> V1{返球の安定性は?}
    W --> W1{スピン重視?}
    X --> X1{適応力重視?}
    Y --> Y1{スピード重視?}
    Z --> Z1{打球感重視?}
    AA --> AA1{バランス重視?}
    AB --> AB1{特定面用?}
    AC --> AC1{スピード重視?}
    AD --> AD1{コントロール重視?}
    AE --> AE1{オールラウンド性能?}
    AF --> AF1{個別のニーズに応じて選択}

    O1 -->|はい| O2[高反発・厚めラバー]
    O1 -->|いいえ| O3[超高反発ラバー]
    P1 -->|はい| P2[高反発・高摩擦ラバー]
    P1 -->|いいえ| P3[高反発・低摩擦ラバー]
    Q1 -->|はい| Q2[高摩擦・中反発ラバー]
    Q1 -->|いいえ| Q3[超高摩擦ラバー]
    R1 -->|ドライブ| R2[中反発・高摩擦ラバー]
    R1 -->|カット| R3[低反発・高摩擦ラバー]
    S1 -->|はい| S2[薄めのラバー]
    S1 -->|いいえ| S3[中程度の厚さのラバー]
    T1 -->|はい| T2[オールラウンドラバー]
    T1 -->|いいえ| T3[特定面用ラバー]
    U1 -->|強い| U2[長粒ラバー（OX）]
    U1 -->|普通| U3[長粒ラバー（スポンジ付き）]
    V1 -->|高い| V2[粒高ラバー]
    V1 -->|普通| V3[中粒ラバー]
    W1 -->|はい| W2[高摩擦ラバー]
    W1 -->|いいえ| W3[中程度の摩擦ラバー]
    X1 -->|はい| X2[オールラウンドラバー]
    X1 -->|いいえ| X3[特定プレイスタイル用ラバー]
    Y1 -->|はい| Y2[攻撃用アンチラバー]
    Y1 -->|いいえ| Y3[守備用アンチラバー]
    Z1 -->|はい| Z2[薄めのラバー]
    Z1 -->|いいえ| Z3[中程度の厚さのラバー]
    AA1 -->|はい| AA2[オールラウンドラバー]
    AA1 -->|いいえ| AA3[特化型ラバー]
    AB1 -->|はい| AB2[特定面用ラバー]
    AB1 -->|いいえ| AB3[汎用性の高いラバー]
    AC1 -->|はい| AC2[高反発・薄めラバー]
    AC1 -->|いいえ| AC3[中反発・薄めラバー]
    AD1 -->|はい| AD2[中反発・中程度の厚さのラバー]
    AD1 -->|いいえ| AD3[高反発・中程度の厚さのラバー]
    AE1 -->|はい| AE2[オールラウンドラバー]
    AE1 -->|いいえ| AE3[バランス型特化ラバー]
    AF1 --> AF2[個別にカスタマイズされたラバー]

    O2 --> AG[ラケット: 重め・硬い, ラバー: 高反発・厚め<br/>パワーと打球感のバランスが良い攻撃的セットアップ]
    O3 --> AH[ラケット: 重め・硬い, ラバー: 超高反発<br/>最大パワーを発揮する攻撃的セットアップ]
    P2 --> AI[ラケット: 中重量, ラバー: 高反発・高摩擦<br/>スピードとスピンを兼ね備えた攻撃的セットアップ]
    P3 --> AJ[ラケット: 中重量, ラバー: 高反発・低摩擦<br/>純粋なスピード重視の攻撃的セットアップ]
    Q2 --> AK[ラケット: 軽め, ラバー: 高摩擦・中反発<br/>スピン重視でコントロールも良い攻撃的セットアップ]
    Q3 --> AL[ラケット: 軽め, ラバー: 超高摩擦<br/>最大スピンを生み出す攻撃的セットアップ]
    R2 --> AM[ラケット: 中重量, ラバー: 中反発・高摩擦<br/>ドライブに適したオールラウンド攻撃用セットアップ]
    R3 --> AN[ラケット: 中重量, ラバー: 低反発・高摩擦<br/>カットに適したオールラウンド守備用セットアップ]
    S2 --> AO[ラケット: 超軽量, ラバー: 薄め<br/>俊敏で繊細な打球感のネットプレイ用セットアップ]
    S3 --> AP[ラケット: 軽め, ラバー: 中程度の厚さ<br/>バランスの取れたネットプレイ用セットアップ]
    T2 --> AQ[ラケット: 軽め, ラバー: オールラウンド<br/>様々な状況に対応できるネットプレイ用セットアップ]
    T3 --> AR[ラケット: 軽め, ラバー: 特定面用<br/>特定のプレイ環境に適したネットプレイ用セットアップ]
    U2 --> AS[ラケット: 長め, ラバー: 長粒&#40;OX&#41;<br/>最大スピン変化を生む守備的セットアップ]
    U3 --> AT[ラケット: 長め, ラバー: 長粒&#40;スポンジ付き&#41;<br/>コントロール重視の守備的セットアップ]
    V2 --> AU[ラケット: 標準サイズ, ラバー: 粒高<br/>安定性重視の守備的セットアップ]
    V3 --> AV[ラケット: 標準サイズ, ラバー: 中粒<br/>バランスの取れた守備的セットアップ]
    W2 --> AW[ラケット: ヘッドライト, ラバー: 高摩擦<br/>スピン重視のスライス用セットアップ]
    W3 --> AX[ラケット: ヘッドライト, ラバー: 中程度の摩擦<br/>コントロール重視のスライス用セットアップ]
    X2 --> AY[ラケット: バランス型, ラバー: オールラウンド<br/>様々な守備スタイルに対応できるセットアップ]
    X3 --> AZ[ラケット: バランス型, ラバー: 特定スタイル用<br/>特定の守備スタイルに特化したセットアップ]
    Y2 --> BA[ラケット: ヘッドヘビー, ラバー: 攻撃用アンチ<br/>攻撃的なカウンター用セットアップ]
    Y3 --> BB[ラケット: ヘッドヘビー, ラバー: 守備用アンチ<br/>守備的なカウンター用セットアップ]
    Z2 --> BC[ラケット: バランス型, ラバー: 薄め<br/>繊細な打球感のカウンター用セットアップ]
    Z3 --> BD[ラケット: バランス型, ラバー: 中程度の厚さ<br/>バランスの取れたカウンター用セットアップ]
    AA2 --> BE[ラケット: オーバーサイズ, ラバー: オールラウンド<br/>オールコート用のバランス型セットアップ]
    AA3 --> BF[ラケット: オーバーサイズ, ラバー: 特化型<br/>オールコート用の特定スタイル重視セットアップ]
    AB2 --> BG[ラケット: ミッドプラス, ラバー: 特定面用<br/>特定コートエリアに特化したセットアップ]
    AB3 --> BH[ラケット: ミッドプラス, ラバー: 汎用性高<br/>特定エリアでも汎用性の高いセットアップ]
    AC2 --> BI[ラケット: 軽量コンパクト, ラバー: 高反発・薄め<br/>高速・軽量なネットプレイ用セットアップ]
    AC3 --> BJ[ラケット: 軽量コンパクト, ラバー: 中反発・薄め<br/>コントロール重視のネットプレイ用セットアップ]
    AD2 --> BK[ラケット: 標準重量, ラバー: 中反発・中厚<br/>コントロール重視の標準的セットアップ]
    AD3 --> BL[ラケット: 標準重量, ラバー: 高反発・中厚<br/>パワー重視の標準的セットアップ]
    AE2 --> BM[ラケット: 中重量バランス型, ラバー: オールラウンド<br/>汎用性の高いオールラウンドセットアップ]
    AE3 --> BN[ラケット: 中重量バランス型, ラバー: バランス型特化<br/>バランス重視の特化型セットアップ]
    AF2 --> BO[ラケット・ラバー: 個別にカスタマイズ<br/>プレイヤーの特性に完全に合わせたセットアップ]